[dependency-groups]
lint = ["ruff"]
dev = [
    { group = "lint"}
]

[tool.uv.sources]
app = { workspace = true }
lib = { workspace = true }
lib-core = { workspace = true }

[tool.uv.workspace]
members = ["libs/*", "app"]
